### Abstract

&emsp; Home cooking is a necessary yet surprisngly high-friction task. Home cooks often struggle with decision fatigue, meaning that despite the countless number of recipes, guides, and cookbooks, home cooks still find themselves asking "What's for dinner?" In addition to the cook's tastes, the home cook also has to consider what ingredients are available to them, what ingredients need to be acquired, is this a recipe that they can feasibly accomplish after work, and is this a recipe that fits within their nutrition plan. The proposed project aims to assist home cooks in making these decisions through both content- and knowledge-based recommendations. Recommendations will be filtered by user's preferences in tastes, what ingredients they have on hand, difficulty, and nutrition. Recommendations will then be ranked according to what the user has enjoyed in the past, by difficulty, and by popularity. Additionally, users will have the option to add ingredients to a shopping cart which can used as a shopping list or as a budgeting tool. Through the proposed project, we hope to reduce the barrier to home cooking by creating a recommendation system that assists with the decision making and planning process of cooking.

### Project Goals

&emsp; The goal of the project is to create a recipe recommendation system that forms both content- and knowledge-based recommendations. Content-based recommendations will be formed by utilizing the ingredient list, difficulty, cuisine, and the nutritional facts. Knowledge-based recommendations will be formed by using the user's taste preferences through what foods and recipes they enjoy, the user's current set of available ingredients, the user's nutrition plan, and the user's skill level. 

&emsp; In addition to forming recommendations, we plan to create a shopping cart that users can utilize as a shopping list or as a budgeting tool.

### Project Plan


&emsp; The major hurdles for the project are to (1) process the data into a suitable form for forming recommendations, (2) create recommendation models, and (3) create a user interface. Data required for this project is tabular and comes from Food.com (formerly GeniusKitchen) hosted on Kaggle.

&emsp; Data processing will cleaning, standardizing, and feature engineering. Processing can be completed in a few days but will likely require revisits throughout the development process.

&emsp; The recommendation phase will take up the majority of the development time. We envision developing multiple recommendation systems with each prioritizing a specific use case such as ease (under 30 minutes), familiarity, popularity, or discovery. We will also need to consider user preferences in these recommendations and their rankings.

&emsp; We plan to create an interactive user interface that can be hosted on a web server. Users will be able to add recipes to a shopping cart.

**Table 1:** Timeline of work plan.

| Phase | Task | Week 4 | Week 5 | Week 6 | Week 7 | Week 8 | Week 9 | Week 10|
|--|--|--|--|--|--|--|--|--|
|Data Acquisition| | &check; | | | | | | |
|Data Processsing| Cleaning | | &check; | | | | |
| | Standardizing | | &check; |
| | Feature Engineering | | &check; |
| Recommendations | | | | &check; | &check; | &check; | &check; |
| Evaluation | | | | | | &check; | &check; |
| User Interface | | | | | | &check; | &check; |
|Write Up| Report and Presentation | | | | | | | &check; |

### Data Sources and EDA

&emsp; The dataset we intend to build our recommender system on - Food.com Recipes and Interactions - was sourced from Kaggle. It consists of over a million ratings of 231,637 recipes by 226,570 Food.com users. Each recipe is described by its ID, name, author ID, date submitted, ingredients, instructions (steps), tags, nutrition, and description. The nutrition column is a list containing each recipe’s calories, total fat, sugar, sodium , protein , and saturated fat; aside from calories, all values are measured as % of daily value (PDV). Other numeric columns describe the number of ingredients and steps. From this information, we intend to derive each recipe’s region of origin (cuisine) and estimate its difficulty. Rating data consists of recipe IDs, user IDs, ratings (out of five stars), and review text. 
The density of the ratings matrix is 2.15 * 10-5. Approximately 73% of all users have only submitted a single rating, and 70% of all recipes have 3 ratings or fewer. Due to this sparsity, we expect that collaborative filtering techniques will be difficult to implement using this dataset. Therefore, we will primarily be exploring content-based filtering and knowledge-based recommendation.

### Data Sample

In [1]:
import pandas as pd

ratings = pd.read_csv('../data/raw/RAW_interactions.csv')
recipes = pd.read_csv('../data/raw/RAW_recipes.csv')

In [2]:
recipes.head()

,name,id,minutes,contributor_id,submitted,tags,nutrition,n_steps,steps,description,ingredients,n_ingredients
0,arriba baked winter squash mexican style,137739,55,47892,2005-09-16,"['60-minutes-or-less', 'time-to-make', 'course...","[51.5, 0.0, 13.0, 0.0, 2.0, 0.0, 4.0]",11,"['make a choice and proceed with recipe', 'dep...",autumn is my favorite time of year to cook! th...,"['winter squash', 'mexican seasoning', 'mixed ...",7
1,a bit different breakfast pizza,31490,30,26278,2002-06-17,"['30-minutes-or-less', 'time-to-make', 'course...","[173.4, 18.0, 0.0, 17.0, 22.0, 35.0, 1.0]",9,"['preheat oven to 425 degrees f', 'press dough...",this recipe calls for the crust to be prebaked...,"['prepared pizza crust', 'sausage patty', 'egg...",6
2,all in the kitchen chili,112140,130,196586,2005-02-25,"['time-to-make', 'course', 'preparation', 'mai...","[269.8, 22.0, 32.0, 48.0, 39.0, 27.0, 5.0]",6,"['brown ground beef in large pot', 'add choppe...",this modified version of 'mom's' chili was a h...,"['ground beef', 'yellow onions', 'diced tomato...",13
3,alouette potatoes,59389,45,68585,2003-04-14,"['60-minutes-or-less', 'time-to-make', 'course...","[368.1, 17.0, 10.0, 2.0, 14.0, 8.0, 20.0]",11,['place potatoes in a large pot of lightly sal...,"this is a super easy, great tasting, make ahea...","['spreadable cheese with garlic and herbs', 'n...",11
4,amish tomato ketchup for canning,44061,190,41706,2002-10-25,"['weeknight', 'time-to-make', 'course', 'main-...","[352.9, 1.0, 337.0, 23.0, 3.0, 0.0, 28.0]",5,['mix all ingredients& boil for 2 1 / 2 hours ...,my dh's amish mother raised him on this recipe...,"['tomato juice', 'apple cider vinegar', 'sugar...",8

In [3]:
ratings.head()

,user_id,recipe_id,date,rating,review
0,38094,40893,2003-02-17,4,Great with a salad. Cooked on top of stove for...
1,1293707,40893,2011-12-21,5,"So simple, so delicious! Great for chilly fall..."
2,8937,44394,2002-12-01,4,This worked very well and is EASY. I used not...
3,126440,85009,2010-02-27,5,I made the Mexican topping and took it to bunk...
4,57222,85009,2011-10-01,5,"Made the cheddar bacon topping, adding a sprin..."

### Expected Complications

1. **Data imbalance** \
&emsp; We will have to find a way to deal with the explicit data bias as users are most likely going to leave reviews on recipes that they really like (5) or don't like (0), making it difficult for models to predict negative ratings. 
2. **Sparse ratings matrix** \
&emsp; A primary challenge will be the high degree of data sparsity inherent in the dataset. With a large ratio of recipes to active reviewers, the user-item interaction matrix will be sparsely populated, potentially leading to 'cold start' issues for new recipes and users with niche tastes.
3. **Feature Engineering from Unstructured Data** \
&emsp; Part of our plan will be to create additional categories to help further filter and differentiate recipes from one another. One issue will be that some techniques used within each recipe may be the same but can be worded differently, so our task will be to create a level of uniformity between these similar steps. Another issue would be pertaining to the ingredients as many ingredients have various names so we will have to decide on what will be the best way to rename ingredients to ensure that they match.
4. **Calculation Complexity** \
&emsp; We are dealing with millions of recipes and hundreds of thousands of users, so calculating similarity matrices may be computationally expensive, thus looking into possible dimensionality reduction techniques that do not make any sacrifices to accuracy may be a solution to look into.
5. **Validation Hurdles** \
&emsp; As this project will be conducted, it will be difficult to truly gauge how successful our recommender will be without A/B testing, so we will need to make use of offline evaluation metrics such as RMSE (Root Mean Squared Error) and MAE (Mean Absolute Error) to validate our systems performance.

### Conclusions

&emsp; The development of a recipe recommendation system using the Food.com dataset presents a unique opportunity to address the complexities of high-dimensional, sparse data in a real-world context. By systematically addressing the complications of data imbalance, matrix sparsity, and unstructured ingredient data, our team aims to build a robust model that moves beyond simple popularity metrics to provide truly personalized user experiences.
Ultimately, this project will demonstrate our ability to implement advanced data science techniques, including dimensionality reduction and entity resolution, to solve the "cold start" problem and deliver meaningful insights from a massive social dataset. The successful completion of this system will not only provide a functional utility for home cooks but also showcase a scalable architecture capable of handling the nuances of human preference and behavioral data.